In [1]:
import pandas as pd
import numpy as np
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score
from sklearn.metrics import accuracy_score
from sklearn.ensemble import GradientBoostingClassifier
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv("PRSA.csv",nrows=500)

In [3]:
df

,No,year,month,day,hour,PM2.5,PM10,SO2,NO2,CO,O3,TEMP,PRES,DEWP,RAIN,wd,WSPM,station
0,1,2013,3,1,0,4,4.0,4.0,7.0,300.0,77.0,-0.7,1023.0,-18.8,0.0,NNW,4.4,Aotizhongxin
1,2,2013,3,1,1,8,8.0,4.0,7.0,300.0,77.0,-1.1,1023.2,-18.2,0.0,N,4.7,Aotizhongxin
2,3,2013,3,1,2,7,7.0,5.0,10.0,300.0,73.0,-1.1,1023.5,-18.2,0.0,NNW,5.6,Aotizhongxin
3,4,2013,3,1,3,6,6.0,11.0,11.0,300.0,72.0,-1.4,1024.5,-19.4,0.0,NW,3.1,Aotizhongxin
4,5,2013,3,1,4,3,3.0,12.0,12.0,300.0,72.0,-2.0,1025.2,-19.5,0.0,N,2.0,Aotizhongxin
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,496,2013,3,21,15,187,202.0,38.0,98.0,1600.0,26.0,7.7,1000.0,-0.8,0.0,ENE,1.4,Aotizhongxin
496,497,2013,3,21,16,188,205.0,40.0,107.0,1600.0,22.0,7.7,999.8,-0.8,0.0,N,1.7,Aotizhongxin
497,498,2013,3,21,17,187,211.0,40.0,114.0,1600.0,20.0,6.9,1000.2,-0.1,0.0,NNW,2.3,Aotizhongxin
498,499,2013,3,21,18,190,221.0,34.0,122.0,1600.0,15.0,6.1,1001.4,0.0,0.0,N,1.1,Aotizhongxin
499,500,2013,3,21,19,202,240.0,24.0,129.0,1700.0,7.0,5.5,1002.5,0.1,0.0,NE,1.4,Aotizhongxin

In [4]:
df_new=df.drop(['No','wd','station'], axis=1)

In [5]:
df_new.isnull().sum()

year      0
month     0
day       0
hour      0
PM2.5     0
PM10      1
SO2       2
NO2       2
CO       13
O3        2
TEMP      0
PRES      0
DEWP      0
RAIN      0
WSPM      0
dtype: int64

In [6]:
test_data = df_new[df_new['CO'].isnull()]

In [7]:
test_data

,year,month,day,hour,PM2.5,PM10,SO2,NO2,CO,O3,TEMP,PRES,DEWP,RAIN,WSPM
75,2013,3,4,3,12,34.0,6.0000,12.0000,NaN,77.0,7.2,1016.9,-11.6,0.0,2.8
124,2013,3,6,4,192,203.0,83.6808,140.4252,NaN,22.0,3.9,1007.3,-6.1,0.0,1.4
171,2013,3,8,3,324,373.0,71.0000,154.0000,NaN,84.0,1.8,997.9,-1.8,0.0,0.0
178,2013,3,8,10,326,844.0,125.9496,179.2269,NaN,84.0,19.1,1000.9,-0.4,0.0,1.9
267,2013,3,12,3,117,127.0,73.0000,81.0000,NaN,47.0,6.4,1005.8,-1.0,0.1,2.2
363,2013,3,16,3,304,332.0,55.0000,108.0000,NaN,44.0,5.6,1017.0,0.4,0.0,1.0
435,2013,3,19,3,33,41.0,15.0000,50.0000,NaN,NaN,0.8,1005.8,-3.0,0.0,1.5
436,2013,3,19,4,31,35.0,15.0000,49.0000,NaN,NaN,0.1,1005.4,-3.5,0.0,1.4
437,2013,3,19,5,29,31.0,13.0000,62.0000,NaN,11.0,0.1,1005.4,-3.8,0.0,1.3
438,2013,3,19,6,32,39.0,13.0000,62.0000,NaN,10.0,0.4,1006.6,-2.8,0.0,1.1
439,2013,3,19,7,30,36.0,10.0000,60.0000,NaN,6.0,1.6,1007.0,-2.4,0.0,1.7
440,2013,3,19,8,34,56.0,11.0000,58.0000,NaN,10.0,3.0,1007.4,-2.9,0.0,2.7
441,2013,3,19,9,38,57.0,26.0000,51.0000,NaN,18.0,2.6,1008.2,-3.5,0.0,2.9

In [8]:
df_new.dropna(inplace=True)

In [9]:
X_train = df_new.drop(['CO'],axis=1)
y_train = df_new['CO']

In [10]:
y_train

0       300.0
1       300.0
2       300.0
3       300.0
4       300.0
        ...
495    1600.0
496    1600.0
497    1600.0
498    1600.0
499    1700.0
Name: CO, Length: 482, dtype: float64

In [11]:
from sklearn.model_selection import GridSearchCV
LR = {'learning_rate':[0.15,0.1,0.10,0.05], 'n_estimators':[100,150,200,250,300], 'max_depth':[1,3,5,7,9]}
tuning = GridSearchCV(estimator = GradientBoostingRegressor(),param_grid = LR,scoring='r2')
tuning.fit(X_train,y_train)
tuning.best_params_, tuning.best_score_

({'learning_rate': 0.05, 'max_depth': 3, 'n_estimators': 100},
 0.3823741449246754)

In [12]:
X_test = test_data[['year','month','day','hour','PM2.5','PM10','SO2','NO2','O3','TEMP','PRES','DEWP','RAIN','WSPM']]

In [13]:
gradientregressor = GradientBoostingRegressor(max_depth=3,n_estimators=100,learning_rate=0.05)

In [14]:
model = gradientregressor.fit(X_train,y_train)
y_pred = model.predict(X_test)

ValueError: Input contains NaN, infinity or a value too large for dtype('float32').

In [ ]:
test_data['y_pred'] = y_pred

In [ ]:
test_data